"""Generate the cross-language conformance vectors.

The firmware and the website each implement this protocol, in different
languages. These vectors are how we find out when they stop agreeing, before a
board does. Python is the source of truth; the TypeScript tests assert against
the same file.

    python3 tools/gen_vectors.py
"""

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

import protocol as p  # noqa: E402

OUTPUT = os.path.join(
    os.path.dirname(__file__), "..", "tests", "vectors", "frames.json"
)

# Payloads picked to exercise the awkward cases: empty, exactly the chunk size,
# exactly the payload limit, multi-byte characters, and text that spells a
# command (which must stay data).
CHECKSUM_CASES = [
    (0, p.KIND_DATA, ""),
    (1, p.KIND_DATA, "a"),
    (0x2A, p.KIND_DATA, "print('hi')"),
    (0xFF, p.KIND_DATA, "x" * 20),
    (0x80, p.KIND_DATA, "y" * p.MAX_PAYLOAD),
    (7, p.KIND_COMMAND, "FIRMCHECK"),
    (8, p.KIND_BEGIN, "12,deadbeef"),
    (9, p.KIND_END, "deadbeef"),
    (10, p.KIND_ACK, "0b,0800"),
    (11, p.KIND_NAK, "05,0800"),
    (12, p.KIND_DATA, "café naïve"),
    (13, p.KIND_DATA, "\U0001f916 robot"),
    (14, p.KIND_DATA, "x04STARTPROG"),
    (15, p.KIND_CONTINUE, "partial line"),
]

PROGRAM_CASES = [
    ("empty", ""),
    ("blank_only", "\n\n\n"),
    ("single", "print('hi')\n"),
    ("crlf", "a = 1\r\nb = 2\r\n"),
    ("blank_lines", "a = 1\n\n\nb = 2\n"),
    ("leading_blank", "\n\na = 1\n"),
    ("no_trailing_newline", "a = 1\nb = 2"),
    ("trailing_space", "x = 'a  '  \n"),
    ("tab_indent", "if True:\n\tprint('tab')\n"),
    ("unicode", "# café naïve 你好\nprint('✓')\n"),
    ("emoji", "# \U0001f916 \U0001f680\n"),
    ("long_line", "x = '" + "y" * 300 + "'\n"),
    ("command_text", "print('a')\nx03ENDUPLD\nx04STARTPROG\nprint('b')\n"),
    ("quotes", "print('single \\'q\\' and \"double\"')\n"),
    ("braces", "data = {'a': {'b': [1, 2]}}\n"),
    (
        "many_lines",
        "".join("value_%03d = %d\n" % (i, i * 7) for i in range(40)),
    ),
]

SPLIT_CASES = [
    "short",
    "x" * p.MAX_PAYLOAD,
    "x" * (p.MAX_PAYLOAD + 1),
    "é" * 200,
    "\U0001f916" * 60,
    "a" + "é" * 150,
]


def main():
    vectors = {
        "_comment": (
            "Generated by tools/gen_vectors.py. Python is the source of truth; "
            "the TypeScript implementation asserts against this file."
        ),
        "constants": {
            "SOH": p.SOH,
            "LF": p.LF,
            "HEADER_LENGTH": p.HEADER_LENGTH,
            "FRAME_OVERHEAD": p.FRAME_OVERHEAD,
            "MAX_PAYLOAD": p.MAX_PAYLOAD,
            "SEQUENCE_MODULO": p.SEQUENCE_MODULO,
            "ACK_EVERY": p.ACK_EVERY,
            "DEFAULT_CREDIT": p.DEFAULT_CREDIT,
            "INITIAL_CREDIT": p.INITIAL_CREDIT,
            "kinds": {
                "DATA": p.KIND_DATA,
                "CONTINUE": p.KIND_CONTINUE,
                "BEGIN": p.KIND_BEGIN,
                "END": p.KIND_END,
                "COMMAND": p.KIND_COMMAND,
                "ACK": p.KIND_ACK,
                "NAK": p.KIND_NAK,
                "REPLY": p.KIND_REPLY,
            },
        },
        "checksums": [
            {
                "seq": seq,
                "kind": kind,
                "payload": payload,
                "checksum": "%04x" % p.frame_checksum(seq, kind, payload.encode()),
                "frame": p.encode_frame(seq, kind, payload).hex(),
            }
            for seq, kind, payload in CHECKSUM_CASES
        ],
        "programs": [
            {
                "name": name,
                "source": source,
                "normalised": p.normalise_program(source),
                "lineCount": p.program_line_count(source),
                "checksum": "%08x" % p.program_checksum(source),
                "frames": [f.hex() for f in p.encode_program(source)],
            }
            for name, source in PROGRAM_CASES
        ],
        "splits": [
            {
                "line": line,
                "pieces": [
                    {"kind": kind, "payload": payload.hex()}
                    for kind, payload in p.split_line(line)
                ],
            }
            for line in SPLIT_CASES
        ],
    }

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w") as handle:
        json.dump(vectors, handle, indent=2, sort_keys=True, ensure_ascii=False)
        handle.write("\n")

    print(
        "wrote %s (%d checksum, %d program, %d split cases)"
        % (
            os.path.relpath(OUTPUT),
            len(vectors["checksums"]),
            len(vectors["programs"]),
            len(vectors["splits"]),
        )
    )


if __name__ == "__main__":
    main()
